name: Deploy MkDocs

on:
  push:
    branches:
      - main   # dispara o deploy em todo push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material mkdocs-jupyter mkdocs-git-revision-date-localized-plugin mkdocs-git-authors-plugin mkdocs-git-committers-plugin mkdocs-minify-plugin

      - name: Build and Deploy
        run: mkdocs gh-deploy --force
